version: '3'
services:
  jenkins:
    build: .
    ports:
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/jenkins.yaml"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
    - ./jenkins_home:/var/jenkins_home